### ISSUE TITLE
OSError: [Errno 22] Invalid argument when doing 2 pass encoding

### ISSUE THREAD

**Issue by rootforbid** [Tatsh/ffmpeg-progress#5]
When doing a 2-pass encoding, 1st pass goes no problem, but the 2nd pass gives me this error:
```
Traceback (most recent call last):
  File "transcode.py", line 76, in <module>
    wait_time=1)
  File "ffmpeg_progress.py", line 137, in start
    on_message=on_message)
  File "ffmpeg_progress.py", line 61, in _display
    vstats_handle.seek(-2, os.SEEK_END)
OSError: [Errno 22] Invalid argument
```

I'm using slight mod of your basic example script:
```python
import subprocess as sp
import sys

from ffmpeg_progress import start


def ffmpeg_1stpass(infile: str, outfile: str, vstats_path: str):
    p = sp.Popen(['ffmpeg',
                  '-y',
                  '-vstats_file', vstats_path,
                  '-probesize', '30G',
                  '-analyzeduration', '10G',
                  '-i', infile,
                  '-map', '0',
                  '-c:v', 'libx264',
                  '-preset', 'ultrafast',
                  '-b:v', '1300k',
                  '-vf', 'scale=720:-2',
                  '-c:s', 'copy',
                  '-pass', '1',
                  '-max_muxing_queue_size', '1024',
                  '-an',
                  '-f', 'matroska',
                  outfile], stdout=sp.PIPE, stderr=sp.PIPE)

    return p.pid


def ffmpeg_2ndpass(infile: str, outfile: str, vstats_path: str):
    p = sp.Popen(['ffmpeg',
                  '-y',
                  '-vstats_file', vstats_path,
                  '-probesize', '30G',
                  '-analyzeduration', '10G',
                  '-i', infile,
                  '-map', '0',
                  '-c', 'copy',
                  '-c:v', 'libx264',
                  '-preset', 'ultrafast',
                  '-b:v', '1300k',
                  '-vf', 'scale=720:-2',
                  '-pass', '2',
                  '-max_muxing_queue_size', '1024',
                  '-c:a', 'ac3',
                  '-movflags', '+faststart',
                  outfile], stdout=sp.PIPE, stderr=sp.PIPE)

    return p.pid


def on_message_handler(percent: float,
                       fr_cnt: int,
                       total_frames: int,
                       elapsed: float):
    sys.stdout.write('\r{:.2f}%'.format(percent))
    sys.stdout.flush()


def on_done_handler():
    print('')


input_file = 'VIDEO.mkv'
output_file = 'VIDEO-enc.mkv'

print('\n1ST PASS ENCODING')

start(input_file,
      '/dev/null',
      ffmpeg_1stpass,
      on_message=on_message_handler,
      on_done=on_done_handler,
      wait_time=1)  # seconds

print('\n2ND PASS ENCODING')

start(input_file,
      output_file,
      ffmpeg_2ndpass,
      on_message=on_message_handler,
      on_done=on_done_handler,
      wait_time=1)
```

Removing `'-pass', '2',` from the ffmpeg_2ndpass function seems to take care of the error, so I'm assuming it's the cause of the error.

Here's the equivalent bash terminal command I use (both run no problem):
1st Pass
```
ffmpeg -loglevel quiet -stats -y \
    -probesize 30G \
    -analyzeduration 10G \
    -i "VIDEO.mkv" \
    -map 0 \
    -c:v libx264 \
    -preset ultrafast \
    -b:v 1300k \
    -vf scale="720:-2" \
    -c:s copy \
    -pass 1 \
    -max_muxing_queue_size 1024 \
    -an \
    -f matroska \
    /dev/null
```
2nd Pass
```
ffmpeg -loglevel quiet -stats -y \
    -probesize 30G \
    -analyzeduration 10G \
    -i "VIDEO.mkv" \
    -map 0 \
    -c copy \
    -c:v libx264 \
    -preset ultrafast \
    -b:v 1300k \
    -vf scale="720:-2" \
    -pass 2 \
    -max_muxing_queue_size 1024 \
    -c:a ac3 \
    -movflags +faststart \
    VIDEO-enc.mkv
```

So I'm not sure why the `-pass 2` argument is a problem.

**Comment by Tatsh** [comment]
This looks like the vstats file path is being reused and it might not exist during the second path.

The error 22 is likely from a call like fseek(handle, -2) where handle is an invalid argument (a closed handle).

**Comment by rootforbid** [comment]
It was my mistake.
I deleted a bunch of rogue ffmpeg log files from previous passes attempt and it works fine now.
