### ISSUE TITLE
Script Does not work

### ISSUE THREAD

**Issue by Wen-Han97** [Tatsh/ffmpeg-progress#8]
```
Traceback (most recent call last):
  File "C:\Users\User\AppData\Roaming\Python\Python38\site-packages\ffmpeg_progress.py", line 129, in start
    fps = eval(probe['streams'][index]['avg_frame_rate'])
  File "<string>", line 1, in <module>
ZeroDivisionError: division by zero

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\User\Desktop\Python\Pyside\FFMpegPython.py", line 25, in <module>
    start('my input file.mp4',
  File "C:\Users\User\AppData\Roaming\Python\Python38\site-packages\ffmpeg_progress.py", line 131, in start
    raise ValueError('Cannot use input FPS')
ValueError: Cannot use input FPS
[Finished in 0.152s]
```

I just Copy the sample code, and change the file name my input file from .mov to .mp4, and I got this error. I don't know what happen. I hope this can be fixed.

**Comment by Tatsh** [comment]
If you know the FPS, try changing `C:\Users\User\AppData\Roaming\Python\Python38\site-packages\ffmpeg_progress.py` line 129. Example with 60 FPS:

```
128    try:
129        fps = 60
```

**Comment by Wen-Han97** [comment]
Traceback (most recent call last):
  File "C:\Users\User\Desktop\Python\Pyside\FFMpegProgress.py", line 25, in <module>
    start('Test.mp4',
  File "C:\Program Files\Python38\lib\site-packages\ffmpeg_progress.py", line 145, in start
    display(total_frames,
  File "C:\Program Files\Python38\lib\site-packages\ffmpeg_progress.py", line 72, in display
    pos_start = os.lseek(vstats_fd, -2, os.SEEK_CUR)
OSError: [Errno 22] Invalid argument

I got another Error After changing (I reinstalled ffmpeg-progress thats why the path is different)

**Comment by Tatsh** [comment]
What is the value of vstats_fd? It comes from the prior call to mkstemp().

I haven't tested this script on windows and wasn't really planning to support it.

I'll accept a pull request if you can get it working but you have to do it from the master branch.

**Comment by tt2468** [comment]
This is likely due to the script looking at the wrong stream for video (eg. looking at an audio stream expecting to find an fps value)

While plenty can be done on @Tatsh side to auto detect which stream to use, the easiest fix for users is to manually ffprobe the file and set the `index` property (default `0`) in the `start()` call to the correct ID of the video stream.

I was having this issue, and found out that it was because a third stream on the file was making ffprobe place the video in index 1 instead of index 0.
